# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32, null=True)),
                ('nextPlayer', models.CharField(default='X', max_length=1)),
                ('xState', models.CharField(default='not_ready', max_length=16)),
                ('oState', models.CharField(default='not_ready', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='playerO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='O', to='app.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='playerX',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='X', to='app.Player'),
        ),
    ]
