# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 05:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[None, None, None, None, None, None, None, None, None], size=None)),
                ('turnState', models.BooleanField(default=True)),
                ('theWinner', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winningPlay', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]]), size=None), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='playerO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='O', to='app.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='playerX',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='X', to='app.Player'),
        ),
    ]
