# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 01:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=['', '', '', '', '', '', '', '', ''], size=9),
        ),
    ]
