# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_tiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tilesPosition',
            field=models.IntegerField(null=True),
        ),
    ]
