# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='theWinner',
        ),
        migrations.AddField(
            model_name='winner',
            name='theWinner',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
