# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170618_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='playerO',
        ),
        migrations.RemoveField(
            model_name='game',
            name='playerX',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
