# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_game_tilesposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='tilesPosition',
            new_name='tilePosition',
        ),
    ]
