# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170618_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turnState',
        ),
    ]
