# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_game_turnstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playerState',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
