# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 03:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170627_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=[None, None, None, None, None, None, None, None, None], size=9),
        ),
    ]
