# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_game_playerstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9), default=['null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'], size=None),
        ),
    ]
