# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170627_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
