# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tilePosition',
        ),
    ]
